name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo add-apt-repository ppa:zhangsongcui3371/fastfetch -y
      - run: sudo apt install fastfetch
      - run: fastfetch
      - uses: mxschmitt/action-tmate@v3