name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make
      - run: ./keyhunt -m bsgs -t 64 -f tests/135.txt -R -b 135 -q -s 10 -k 1024
