name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make
      - run: ./keyhunt -m bsgs -t 64 -f tests/125.txt -R -b 125 -q -S -s 10 -n 0x100000000000 -k 4096
